title: Keep Stoga Safe
logo: profile.png
description: student-run. not a club. not organized by Conestoga admin or faculty. goal, respect, and activism-oriented.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
